import matplotlib.pyplot as plt
def scatter(ax, x, y):
  ax.scatter(x, y, s=0.5)
fig, ax = plt.subplots(1,1, constrained_layout=True)
scatter(ax, [1.3, ], [4.8, ])
scatter(ax, [5, 4.1, ], [6, 4.1, ])
scatter(ax, [1, ], [2, ])
scatter(ax, [3.1, ], [3.22, ])
scatter(ax, [4.3, ], [3.1, ])
scatter(ax, [3.42, ], [2.18, ])
scatter(ax, [4.2, ], [2.5, ])
r = plt.Rectangle([1, 2], 4, 4, fill=False)
ax.add_patch(r)
r = plt.Rectangle([1, 4], 2, 2, fill=False)
ax.add_patch(r)
r = plt.Rectangle([3, 4], 2, 2, fill=False)
ax.add_patch(r)
r = plt.Rectangle([1, 2], 2, 2, fill=False)
ax.add_patch(r)
r = plt.Rectangle([3, 2], 2, 2, fill=False)
ax.add_patch(r)
r = plt.Rectangle([3, 3], 1, 1, fill=False)
ax.add_patch(r)
r = plt.Rectangle([4, 3], 1, 1, fill=False)
ax.add_patch(r)
r = plt.Rectangle([3, 2], 1, 1, fill=False)
ax.add_patch(r)
r = plt.Rectangle([4, 2], 1, 1, fill=False)
ax.add_patch(r)
ax.axis('equal')
plt.show()
